### ISSUE TITLE
Admin acc

### ISSUE THREAD

**Issue by boradmir** [Gamer08YT/Hostinger#1]
there is no admin account, how can ı register my acc?

**Comment by Gamer08YT** [comment]
Hey,
simply add an Account inside the Database and set Rank to 1 ;)

**Comment by boradmir** [comment]
I did, but it is not possible, can u create for me insert into code?

**Comment by Gamer08YT** [comment]
INSERT INTO `kresu24_user` (`id`, `first_name`, `last_name`, `email`, `password`, `birthday`, `rank`, `key`) VALUES (NULL, 'Max', 'Mustermann', 'max.mustermann@provider.tld', 'password-in-base64', '2020-05-31', '1', '');
