### ISSUE TITLE
DiscordBot.jar

### ISSUE THREAD

**Issue by Faflixt** [Gamer08YT/Hostinger#3]
Hello,

Where can I find the DiscordBot.jar?

**Comment by Gamer08YT** [comment]
You have to call your Binary from the Bot "DiscordBot.jar" that Hostinger can run it.
Sorry, but Hostinger is about 4yr old, it has not many features.

You can simply add some other Languages via the commands...

Like Java:
screen -SL ${SCREEN} -Logfile ./triox-server.log java -jar "$BIN$SERVER_STARTBINARY_JAVA"

or Node
screen -SL ${SCREEN} -Logfile ./triox-server.log node "$BIN$SERVER_STARTBINARY_JS"
